### PR TITLE
Py12box luke

### PR DESCRIPTION
**Pull request by lukewestern**
1) Made strat_lifetime_tune run with new model class
2) Now uses zero ics if no ic file is supplied
3) Estimates strat lifetime in each box on the fly if no lifetime file provided. Uses file inputs/lifetimes.csv – I expect this to be deleted at some point but works as a place holder.

### CODE REVIEW

**Comment by mrghg** [comment]
inputs/lifetimes.csv file not added?

Four tests failing due to path issues

**Comment by mrghg** [comment]
I've fixed some path issues in the above commit, but there's still something wrong with the lifetimes test.

Can you use pathlib syntax for checking files (i.e. don't need os.path...)?

Will be easier if we can avoid writing a lifetime file after auto tuning (i.e. do it in memory)

**Comment by mrghg** [comment]
Tests pass now. Just need that lifetimes file.

**Comment by lukewestern** [comment]
Should all now be done, and passes tests.

**Comment by mrghg** [comment]
I've added some example files and the start of a test for the lifetime tuning. however, I just get some kind of infinite recursion. Not sure what's going on. I haven't finished the test...

Also, seems problematic to have if statements testing for a missing lifetimes files and target lifetimes, but not some other combination.

Shouldn't we move the "default" lifetimes out of the tuning function and instead pass the relevant default lifetime to the "target_lifetime" argument?

Run out of time, but can try to look at this later in the week, and will add in other lifetimes too.

**Review by mrghg — APPROVED** [review]

**Comment by mrghg** [comment]
Resolves issue #1 and issue #6

**Pull request merged**
