### PR TITLE
Updated losses

### PR DESCRIPTION
**Pull request by lukewestern**
Update losses to be consistent with most recent JPL report and Ozone Assessment.
CH4 uses stratospheric loss fro IPCC AR5.

### CODE REVIEW

**Comment by mrghg** [comment]
So where it says "WMO 2022 JPL 2020", does that mean that the OH is from JPL and other sinks from WMO?

**Review by mrghg — APPROVED** [review]

**Review by mrghg — CHANGES_REQUESTED** [review]
Sorry, I approved too early. Tests are failing, because some of the hard-wired lifetimes are no longer valid

**Comment by lukewestern** [comment]
> So where it says "WMO 2022 JPL 2020", does that mean that the OH is from JPL and other sinks from WMO?

Yes, this is what I mean. It was just intended to be a list of references.

Fixed the tests now and all pass.

**Review by mrghg — APPROVED** [review]
Looks good.

**Pull request merged**
